USE [master]
GO

/****** Object:  Database [Sufetravel]    Script Date: 3/4/2019 10:19:45 AM ******/
CREATE DATABASE [Sufetravel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sufetravel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Sufetravel.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sufetravel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Sufetravel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Sufetravel] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sufetravel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sufetravel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sufetravel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sufetravel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sufetravel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sufetravel] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sufetravel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sufetravel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sufetravel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sufetravel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sufetravel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sufetravel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sufetravel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sufetravel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sufetravel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sufetravel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sufetravel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sufetravel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sufetravel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sufetravel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sufetravel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sufetravel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sufetravel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sufetravel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sufetravel] SET  MULTI_USER 
GO

ALTER DATABASE [Sufetravel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sufetravel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sufetravel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sufetravel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sufetravel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sufetravel] SET QUERY_STORE = OFF
GO

USE [Sufetravel]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Sufetravel] SET  READ_WRITE 
GO

